In [ ]:
import numpy as np

class VacuumCleaner:
    def __init__(self, rows=5, cols=5):
        self.rows, self.cols = rows, cols
        self.grid = self.get_user_grid()
        self.position = [0, 0]  
        self.visited = set()
        self.visited.add((0, 0))
        self.stack = [(0, 0)]  
        self.actions = []  
        self.moves = [(-1, 0), (1, 0), (0, -1), (0, 1)] 

    def get_user_grid(self):
        print("Enter the 5x5 grid (0 for clean, 1 for dirty). Input each row as 5 space-separated integers.")
        grid = []
        for i in range(self.rows):
            while True:
                try:
                    row = input(f"Enter row {i+1}: ").strip().split()
                    if len(row) != self.cols:
                        print(f"Error: Please enter exactly {self.cols} values.")
                        continue
                    row = [int(x) for x in row]
                    if all(x in [0, 1] for x in row):
                        grid.append(row)
                        break
                    else:
                        print("Error: Values must be 0 or 1.")
                except ValueError:
                    print("Error: Please enter valid integers (0 or 1).")
        return grid

    def sense_dirt(self):
        x, y = self.position
        return self.grid[x][y] == 1

    def clean(self):
        x, y = self.position
        if self.grid[x][y] == 1:
            self.grid[x][y] = 0
            self.actions.append(f"Clean at ({x}, {y})")
            print(f"\n{self.actions[-1]}")
            print(np.array(self.grid))
            return True
        return False

    def is_valid_move(self, x, y):
        return 0 <= x < self.rows and 0 <= y < self.cols

    def is_done(self):
        return all(self.grid[x][y] == 0 for x in range(self.rows) for y in range(self.cols))

    def dfs_clean(self):
        while self.stack:
            x, y = self.position
            
            if self.sense_dirt():
                self.clean()
            
            neighbors = []
            for dx, dy in self.moves:
                new_x, new_y = x + dx, y + dy
                if self.is_valid_move(new_x, new_y) and (new_x, new_y) not in self.visited:
                    neighbors.append((new_x, new_y))
            if neighbors:
                
                next_pos = neighbors[0]
                self.stack.append(next_pos)
                self.visited.add(next_pos)
                self.position = list(next_pos)
                self.actions.append(f"Move to {next_pos}")
                print(f"\n{self.actions[-1]}")
                print(np.array(self.grid))
            else:
                
                self.stack.pop()
                if self.stack:
                    self.position = list(self.stack[-1])
                    self.actions.append(f"Backtrack to {self.position}")
                    print(f"\n{self.actions[-1]}")
                    print(np.array(self.grid))
            
            if self.is_done():
                break

    def run(self):
        print("Initial grid:")
        print(np.array(self.grid))
        self.dfs_clean()
        print("\nFinal grid:")
        print(np.array(self.grid))

if __name__ == "__main__":
    vacuum = VacuumCleaner()
    vacuum.run()

Enter the 5x5 grid (0 for clean, 1 for dirty). Input each row as 5 space-separated integers.
Initial grid:
[[1 1 1 1 1]
 [0 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

Clean at (0, 0)
[[0 1 1 1 1]
 [0 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

Move to (1, 0)
[[0 1 1 1 1]
 [0 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

Move to (2, 0)
[[0 1 1 1 1]
 [0 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

Clean at (2, 0)
[[0 1 1 1 1]
 [0 1 1 1 1]
 [0 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

Move to (3, 0)
[[0 1 1 1 1]
 [0 1 1 1 1]
 [0 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

Clean at (3, 0)
[[0 1 1 1 1]
 [0 1 1 1 1]
 [0 1 1 1 1]
 [0 1 1 1 1]
 [1 1 1 1 1]]

Move to (4, 0)
[[0 1 1 1 1]
 [0 1 1 1 1]
 [0 1 1 1 1]
 [0 1 1 1 1]
 [1 1 1 1 1]]

Clean at (4, 0)
[[0 1 1 1 1]
 [0 1 1 1 1]
 [0 1 1 1 1]
 [0 1 1 1 1]
 [0 1 1 1 1]]

Move to (4, 1)
[[0 1 1 1 1]
 [0 1 1 1 1]
 [0 1 1 1 1]
 [0 1 1 1 1]
 [0 1 1 1 1]]

Clean at (4, 1)
[[0 1 1 1 1]
 [0 1 1 1 1]
 [0 1 1 1 1]
 [0 1 1 1 1]
 [0 0 1 1 1]]

M